# Generated by Django 5.0.3 on 2024-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="hostel",
            field=models.CharField(
                choices=[
                    ("Manimala", "Manimala"),
                    ("Meenachil", "Meenachil"),
                    ("Sahayadri", "Sahayadri"),
                    ("Girls Hostel", "Girls Hostel"),
                    ("Outside", "Outside"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="roomno",
            field=models.IntegerField(default=0),
        ),
    ]
