# Generated by Django 5.0.3 on 2024-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAuth", "0005_userprofile_phoneno_userprofile_role_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="rollno",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phoneno",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
