# Generated by Django 5.0.3 on 2024-03-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAuth", "0006_alter_customer_rollno_alter_userprofile_phoneno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
