# Generated by Django 5.0.3 on 2024-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_remove_product_id_product_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
