# Generated by Django 5.0.3 on 2024-03-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0005_order"),
        ("UserAuth", "0002_customer_hostel_customer_roomno"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserAuth.customer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items_json",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.CharField(
                choices=[
                    ("OAT", "OAT"),
                    ("Football Ground", "Football Ground"),
                    ("Volleyball Ground", "Volleyball Ground"),
                    ("Admin Block", "Admin Block"),
                    ("Manimala Hostel", "Manimala Hostel"),
                    ("Meenachil Hostel", "Meenachil Hostel"),
                    ("Sahayadri Hostel", "Sahayadri Hostel"),
                    ("Girls Hostel", "Girls Hostel"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
