# Generated by Django 5.0.3 on 2024-03-28 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0009_alter_order_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
