# Generated by Django 5.0.3 on 2024-03-28 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0012_remove_order_items_json_order_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="items_json",
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 28, 6, 2, 44, 41761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
