# Generated by Django 5.0.3 on 2024-03-28 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0013_remove_order_products_order_items_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(to="Home.product"),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 28, 6, 23, 10, 352849, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
