# Generated by Django 5.0.3 on 2024-03-28 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0015_alter_order_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 28, 17, 5, 44, 488648, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
