# Generated by Django 5.0.3 on 2024-03-28 18:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0016_alter_order_date_created"),
        ("UserAuth", "0008_alter_admin_aadharno_alter_deliverer_aadharno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 28, 18, 53, 11, 726261, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items_json", models.CharField(max_length=5000, null=True)),
                ("isActive", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserAuth.customer",
                    ),
                ),
            ],
        ),
    ]
