# Generated by Django 5.0.3 on 2024-03-29 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0017_alter_order_date_created_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 29, 3, 38, 34, 100456, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Packing", "Packing"),
                    ("Assigned Deliverer", "Assigned Deliverer"),
                    ("Out for delivery", "Out for delivery"),
                    ("Delivered", "Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
