# Generated by Django 5.0.3 on 2024-03-29 08:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0018_alter_order_date_created_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        choices=[
                            ("OAT", "OAT"),
                            ("Football Ground", "Football Ground"),
                            ("Volleyball Ground", "Volleyball Ground"),
                            ("Admin Block", "Admin Block"),
                            ("New Academic Block Stairs", "New Academic Block Stairs"),
                            ("Manimala Hostel", "Manimala Hostel"),
                            ("Meenachil Hostel", "Meenachil Hostel"),
                            ("Sahayadri Hostel", "Sahayadri Hostel"),
                            ("Girls Hostel", "Girls Hostel"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 29, 8, 26, 59, 105697, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_name", models.CharField(max_length=200)),
                ("locations", models.ManyToManyField(to="Home.location")),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="location",
            field=models.ForeignKey(
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Home.location",
            ),
        ),
    ]
