# Generated by Django 5.0.3 on 2024-03-29 17:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0025_alter_order_date_created"),
        ("UserAuth", "0008_alter_admin_aadharno_alter_deliverer_aadharno"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deliverer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserAuth.deliverer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 29, 17, 24, 45, 966274, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
