# Generated by Django 5.0.3 on 2024-03-30 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0026_order_deliverer_alter_order_date_created"),
        ("UserAuth", "0008_alter_admin_aadharno_alter_deliverer_aadharno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 30, 16, 48, 44, 142165, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="deliverer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserAuth.deliverer",
            ),
        ),
    ]
