# Generated by Django 5.0.3 on 2024-04-06 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0027_alter_order_date_created_alter_order_deliverer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 20, 8, 37, 190788, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
