# Generated by Django 5.0.3 on 2024-04-07 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0028_order_paid_alter_order_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 7, 16, 44, 0, 489971, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
