<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-07 16:44
=======
# Generated by Django 5.0.3 on 2024-04-09 08:29
>>>>>>> 36a8693aa13e415a9d37648b667455b46afde6f9

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("Home", "0028_order_paid_alter_order_date_created"),
=======

    dependencies = [
        ('Home', '0028_order_paid_alter_order_date_created'),
>>>>>>> 36a8693aa13e415a9d37648b667455b46afde6f9
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name="order",
            name="paid",
        ),
        migrations.AlterField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 7, 16, 44, 0, 489971, tzinfo=datetime.timezone.utc
                )
            ),
=======
            model_name='order',
            name='paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 8, 29, 38, 350255, tzinfo=datetime.timezone.utc)),
>>>>>>> 36a8693aa13e415a9d37648b667455b46afde6f9
        ),
    ]
